export default function AIReport({ report, demoMode, loading, error }) {
  const text = typeof report === 'string' ? report : report?.report || '';
  return (
    <section className="panel">
      <div className="panel-head">
        <div>
          <p className="eyebrow">Incident narrative</p>
          <h2>AI SECURITY REPORT</h2>
        </div>
        <span className={`sys-pill ${demoMode ? 'is-demo' : 'is-online'}`}>
          {demoMode ? 'DEMO AI REPORT' : 'GENERATED BY AI'}
        </span>
      </div>
      {loading && !text ? <p className="state-msg">Generating report…</p> : null}
      {error ? <p className="state-msg is-error">{error}</p> : null}
      {!loading && !error && !text ? (
        <p className="state-msg">No report is available yet.</p>
      ) : null}
      {text ? <div className="report-body">{text}</div> : null}
    </section>
  );
}
